### ISSUE TITLE
项目报错

### ISSUE THREAD

**Issue by kira2015** [xuyisheng/flutter_dojo#16]
**Describe the bug**
Flutter版本1.22.3，项目运行不了

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/14231117/99229917-9dbb4c80-2829-11eb-9646-a2b6706e4d08.png">

**Comment by xuyisheng** [comment]
SDK问题，设置environment:
  sdk: ">=2.8.0 <3.0.0"即可
