### ISSUE TITLE
问一下用的依赖的是flutter什么版本

### ISSUE THREAD

**Issue by zk184174875** [xuyisheng/flutter_dojo#3]
问一下用的依赖的是flutter什么版本，dart是什么版本

**Comment by xuyisheng** [comment]
Flutter 1.12.13+hotfix.8 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (3 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0
