### ISSUE TITLE
错误的路径导致App内无法查看源码

### ISSUE THREAD

**Issue by jaredtech** [xuyisheng/flutter_dojo#4]
源文件的名称是下划线区分单词，而跳转markdown显示源代码的时候却是
`MaterialPageRoute(
       builder: (context) => MarkdownPage(codePath + title.toLowerCase() + '.dart'),
 )`
直接将‘页面标题’转为小写字母，导致很多界面，点击查看源码的时候打开的路径异常而无法获取到正确的源码文件，从而没法实现跳转。

**Comment by xuyisheng** [comment]
嗯，有些界面没法跳转源码界面是因为路径的问题，有些Demo在多个页面复用了，导致在其它界面就不能展示，目前这块还没想好如何重构，有好的建议可以提pr，谢谢

**Comment by xuyisheng** [comment]
2.0已修复
