### ISSUE TITLE
CustomPaint

### ISSUE THREAD

**Issue by LaoXiZi** [xuyisheng/flutter_dojo#6]
![2020-03-07_144852](https://user-images.githubusercontent.com/23638133/76138419-d7c13580-6082-11ea-89e3-b10f75bf3504.png)

**Comment by xuyisheng** [comment]
有很多Demo只是为了演示如何使用，所以并没有做的非常完善，dojo只给开发者提供如何去做，已经怎么去做，但是要做的完善，需要开发者自己优化，图中的问题已修复，多谢提醒~
